[Interface]
PrivateKey = AH/knP34hDZB6+YRTv9Zq1Gm6FdMWkgr3bCtCOOi+X0=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = DutvYBPwBcYx2+dXNj/vfrS/udqhQurdrZ+DPVDwPHc=
Endpoint = 207.246.107.152:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
