[Interface]
PrivateKey = EOlE4gKoZq+3PwkI43NabxK1sMUMNZDcoOoJFaLPN0o=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = vwQR+42ei2+MlJiyTa8uYjuDEfkkIoL4Lp55FwM5p14=
Endpoint = 149.28.140.88:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
