[Interface]
PrivateKey = 2DQP0VRle8x3VpQAJTkEl9QtjlEX5ISsImnzmB4wUEs=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = IhA2JvxqiB7Voq6jEHbWZ1BWq2VohX+r4t40SHGSV1U=
Endpoint = 64.176.72.123:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
