[Interface]
PrivateKey = yHX8yt7E5jHt9bnLyAL4DhT7qTjh/34uvYU4Fpd4eFA=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = cMnCeECXA1PiFau9gxGNAaPufOYy+4i272Zix5kznks=
Endpoint = 45.76.84.87:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
